// Auto-generated by meta_codegen.py - DO NOT EDIT
#include "engine/registry.h"
#include "engine/physics_system.h"
#include "server/player_sao.h"
#include "serverenvironment.h"
#include "world/dimension_manager.h"

void EngineRegistry::register_all_reflected() {
    // Reflection for DimensionManager
    EngineRegistry::expose_property("dimensions", "active_dimension", &DimensionManager::m_active_dimension);
    EngineRegistry::expose_property("dimensions", "dimension_list", &DimensionManager::m_dimension_list);
    // Reflection for PhysicsSystem
    EngineRegistry::expose_property("physics", "gravity", &PhysicsSystem::gravity);
    EngineRegistry::expose_property("physics", "air_resistance", &PhysicsSystem::air_resistance);
    EngineRegistry::expose_property("physics", "terminal_velocity", &PhysicsSystem::terminal_velocity);
    // Reflection for PlayerSAO
    EngineRegistry::expose_property("player", "breath", &PlayerSAO::m_breath);
    EngineRegistry::expose_property("player", "pitch", &PlayerSAO::m_pitch);
    EngineRegistry::expose_property("player", "fov", &PlayerSAO::m_fov);
    EngineRegistry::expose_property("player", "wanted_range", &PlayerSAO::m_wanted_range);
    EngineRegistry::expose_property("player", "camera_inverted", &PlayerSAO::m_camera_inverted);
    // Reflection for ServerEnvironment
    EngineRegistry::expose_property("world", "game_time", &ServerEnvironment::m_game_time);
    EngineRegistry::expose_property("world", "time_of_day", &ServerEnvironment::m_time_of_day);
}
