#!/usr/bin/env python3
import os
import re
import sys

# Scans source files for REFLECT_* macros and generates C++ binding code.

def scan_files(src_dir):
    # Map of class name -> list of (type, name)
    reflected_classes = {}

    # regex for class definition: class Name ... {
    # This avoids forward declarations class Name;
    class_def_re = re.compile(r'class\s+(\w+)(?:\s+final)?(?:\s*:\s*[^{]+)?\s*\{')
    reflect_class_re = re.compile(r'REFLECT_CLASS\s*\(\)')
    reflect_field_re = re.compile(r'REFLECT_FIELD\s*\(\)\s+([\w:<>*&]+)\s+(\w+)')

    for root, _, files in os.walk(src_dir):
        for file in files:
            if file.endswith(('.h', '.hpp')):
                path = os.path.join(root, file)
                with open(path, 'r', encoding='utf-8', errors='ignore') as f:
                    content = f.read()
                    if 'REFLECT_CLASS' not in content:
                        continue

                    # Find all classes that have REFLECT_CLASS
                    current_pos = 0
                    while True:
                        class_match = class_def_re.search(content, current_pos)
                        if not class_match:
                            break

                        class_name = class_match.group(1)
                        class_start = class_match.start()

                        # Find the end of this class definition (matching braces)
                        brace_count = 1
                        search_pos = class_match.end()
                        class_end = -1
                        while search_pos < len(content):
                            if content[search_pos] == '{':
                                brace_count += 1
                            elif content[search_pos] == '}':
                                brace_count -= 1
                                if brace_count == 0:
                                    class_end = search_pos
                                    break
                            search_pos += 1

                        if class_end == -1:
                            current_pos = class_match.end()
                            continue

                        class_body = content[class_start:class_end]

                        if reflect_class_re.search(class_body):
                            fields = []
                            field_matches = reflect_field_re.finditer(class_body)
                            for m in field_matches:
                                fields.append(m.group(2))

                            if fields:
                                reflected_classes[class_name] = {
                                    "header": os.path.relpath(path, src_dir),
                                    "fields": fields
                                }

                        current_pos = class_end

    return reflected_classes

def generate_cpp(data, output_path):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write('// Auto-generated by meta_codegen.py - DO NOT EDIT\n')
        f.write('#include "engine/registry.h"\n')
        # Sort headers to ensure deterministic output
        headers = sorted(set(info["header"] for info in data.values()))
        for header in headers:
            f.write(f'#include "{header}"\n')

        f.write('\nvoid EngineRegistry::register_all_reflected() {\n')
        for class_name in sorted(data.keys()):
            info = data[class_name]
            f.write(f'    // Reflection for {class_name}\n')

            # Custom mapping for system names
            sys_name = class_name.lower()
            if "serverenvironment" in sys_name: sys_name = "world"
            elif "physicssystem" in sys_name: sys_name = "physics"
            elif "playersao" in sys_name: sys_name = "player"
            elif "dimensionmanager" in sys_name: sys_name = "dimensions"

            for field in info["fields"]:
                # Strip 'm_' prefix if present for Lua-side name
                lua_field_name = field[2:] if field.startswith('m_') else field
                f.write(f'    EngineRegistry::expose_property("{sys_name}", "{lua_field_name}", &{class_name}::{field});\n')
        f.write('}\n')

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: meta_codegen.py <src_dir> <output_cpp>")
        sys.exit(1)
    src_dir = sys.argv[1]
    output_path = sys.argv[2]
    data = scan_files(src_dir)
    generate_cpp(data, output_path)
